# Generated by Django 2.2 on 2020-03-14 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='access',
            field=models.CharField(choices=[('public', 'Общий'), ('hidden', 'Скрытый'), ('private', 'Приватный')], default='public', max_length=20, verbose_name='Доступ'),
        ),
        migrations.AlterField(
            model_name='files',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Подпись'),
        ),
    ]
